# Generated by Django 4.0.1 on 2022-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coover_picture',
            field=models.ImageField(default='default-book-picture.jpg', upload_to=''),
        ),
    ]
